### ISSUE TITLE
Move PlayVoiceLabel and PlaySound to Feedback

### ISSUE THREAD

**Issue by Yoric** [project-lighthouse/camera-app.ios#12]
`PlayVoiceLabel` and `PlaySound` are called from C++ and implemented in Cocoa. Currently, they live in `Bridge`, which means that they can be called from Cocoa but not from C++. They should move to `Feedback`, where they can be put to good use :)

**Comment by azasypkin** [comment]
Mostly covered in https://github.com/project-lighthouse/camera-app.ios/commit/33f362c84067885eb8a347db73bc17f6caef751a and https://github.com/project-lighthouse/camera-app.ios/commit/b57cad2dacbc1ff986df3fc3d92cec701c3c1e67. Looks good enough for now, we'll make a separation even clearer at some point when our codebase is more or less stable.
