### ISSUE TITLE
Use opencv2/imgcodecs/ios.h utilities for UIImage <-> cv::Mat conversion instead of custom ones

### ISSUE THREAD

**Issue by azasypkin** [project-lighthouse/camera-app.ios#48]
It turned out that we already have `MatToUIImage` and `UIImageToMat` in OpenCV iOS framework, let's use them (and have less bugs we're responsible for)!

**Comment by Yoric** [comment]
@azasypkin Did you check about the memory issues?

**Comment by azasypkin** [comment]
@Yoric will be investigating them in https://github.com/project-lighthouse/camera-app.ios/issues/53. But the problem looked the same for both our custom implementation of UIImage<->cv::Mat conversion and the one that is provided by OpenCV.

**Comment by Yoric** [comment]
I see an artifact when I run the test on the simulator (see the top of the image). I may be wrong, but I believe that the artifact was not visible before that patch.
